### ISSUE TITLE
上传文件怎么实现, 想学习一下, 这边什么时候完成呀

### ISSUE THREAD

**Issue by xiaokyo** [hfh1999/baiduyun_api#1]

**Comment by hfh1999** [comment]
你好，关于上传文件的官方文档在这里(https://pan.baidu.com/union/doc/3ksg0s9ye) ，根据它的要求，进行分步上传即可。由于最近较忙，rust的baiduapi可能要再拖一会了，因为要把我的其他项目先完成 :)。
要是你还有疑问可以再联系我。

**Comment by xiaokyo** [comment]
> 你好，关于上传文件的官方文档在这里(https://pan.baidu.com/union/doc/3ksg0s9ye) ，根据它的要求，进行分步上传即可。由于最近较忙，rust的baiduapi可能要再拖一会了，因为要把我的其他项目先完成 :)。 要是你还有疑问可以再联系我。

我文档知道, 只是卡在rust创建分片了, 不是很理解rust的分片到底是怎么弄, 是buffer读取还是啥

**Comment by hfh1999** [comment]
关于分片，其实本质上就是文件的分段处理。
比如我们有一个文件大小为13M，并且我们使用4M大小的片进行分割。
那么总共就有4个片大小分别为: 4,4,4,1。

对于小文件我们当然可以把它读入到一个buffer中，比如String中，但是如果是大于1GB的文件的话，就不大可取了，
因为用户的内存是有限的，如果全用来当做文件buffer的话就太可惜了。

我有个不成熟的想法，要是你有意见可以探讨一下:

还是上面的例子。
1.关于预上传阶段。
首先打开想要上传的文件，每次读取4MB，计算其MD5，等读到文件末尾时，所有片的MD5都会计算完毕。

2.关于分段上传阶段。
利用seek调用退回之前文件的开始处，重新读取，每次读取4MB后构造一个相应的POST请求发送出去，直到文件末尾，最终文件就可以发送完成。

伪代码大概是下面的样子，就不进行错误处理了:

```
let file = open("test.mp4");
let md5_arr = [];
while (file not end)
{
  buffer = read(file,4000000); // 读入4MB
  md5_arr.append( calculate_md5(buffer)); // 计算md5并存入数组
}
send_post(md5_arr); // 构造POST请求进行预上传

file.seek(0); // 返回文件开始
while(file not end)
{
  buffer = read(file,4000000); // 读入4MB
  send_post(data); //  构造POST进行分段上传。
}
```

**Comment by xiaokyo** [comment]
> 关于分片，其实本质上就是文件的分段处理。 比如我们有一个文件大小为13M，并且我们使用4M大小的片进行分割。 那么总共就有4个片大小分别为: 4,4,4,1。
> 
> 对于小文件我们当然可以把它读入到一个buffer中，比如String中，但是如果是大于1GB的文件的话，就不大可取了， 因为用户的内存是有限的，如果全用来当做文件buffer的话就太可惜了。
> 
> 我有个不成熟的想法，要是你有意见可以探讨一下:
> 
> 还是上面的例子。 1.关于预上传阶段。 首先打开想要上传的文件，每次读取4MB，计算其MD5，等读到文件末尾时，所有片的MD5都会计算完毕。
> 
> 2.关于分段上传阶段。 利用seek调用退回之前文件的开始处，重新读取，每次读取4MB后构造一个相应的POST请求发送出去，直到文件末尾，最终文件就可以发送完成。
> 
> 伪代码大概是下面的样子，就不进行错误处理了:
> 
> ```
> let file = open("test.mp4");
> let md5_arr = [];
> while (file not end)
> {
>   buffer = read(file,4000000); // 读入4MB
>   md5_arr.append( calculate_md5(buffer)); // 计算md5并存入数组
> }
> send_post(md5_arr); // 构造POST请求进行预上传
> 
> file.seek(0); // 返回文件开始
> while(file not end)
> {
>   buffer = read(file,4000000); // 读入4MB
>   send_post(data); //  构造POST进行分段上传。
> }
> ```

感谢, 只是不知道怎么使用rust如何实现这个读取4mb的操作

**Comment by hfh1999** [comment]
那这个就设计Rust语言的基本文件操作了，
这个你可能需要看一下官方标准库的fs部分:
[https://doc.rust-lang.org/std/fs/index.html](https://doc.rust-lang.org/std/fs/index.html)

以及Read Trait 部分:
[https://doc.rust-lang.org/std/io/trait.Read.html](https://doc.rust-lang.org/std/io/trait.Read.html)

在Rust中文件实现了```Read Trait``` ，```Read Trait```中的各个方法你都可以看看。

学习Rust的基本方法就是查阅标准库和文档，在windows上在命令行上输入``` rustup doc ``` 来打开离线文档

**Comment by xiaokyo** [comment]
感谢回复

**Comment by xiaokyo** [comment]
我这边写到char的传值了
https://github.com/xiaokyo/rs-baidu-sdk/blob/master/src/lib/pan.rs#L388
查百度都是传的不对， 死活不知道是什么样的格式，
有空的话帮我看看嘛

**Comment by xiaokyo** [comment]
写的稍稍有点乱

**Comment by hfh1999** [comment]
你好，能请你展示一下baidu的错误码，以及更多的调试信息吗。

我的一个猜测是可能和百度云的文件上传权限有关，请看文档中的这部分:

![image](https://user-images.githubusercontent.com/35996537/179794904-465f500f-9302-4b97-b150-6a9ee4bc4fd3.png)

这是在[https://pan.baidu.com/union/document/basic#%E8%83%BD%E5%8A%9B%E8%AF%B4%E6%98%8E](https://pan.baidu.com/union/document/basic#%E8%83%BD%E5%8A%9B%E8%AF%B4%E6%98%8E)中的。

**Comment by xiaokyo** [comment]
返回的是400, 参数错误, 而且参数只有这个file
其他都是url参数, 所以我断定是file的格式还是不对

**Comment by xiaokyo** [comment]
但是又不知道是哪里不对, 很苦恼

**Comment by xiaokyo** [comment]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/22857964/179879315-4bbaf9cf-5262-4784-82a3-679fd70d7c2b.png">
这是完整的返回

**Comment by xiaokyo** [comment]
file为空的时候是正常返回, 但是file的格式还是不知道怎么传, 传Vec\<u8\>还是传Vec\<char\>都是接口返回file字段错误
<img width="646" alt="image" src="https://user-images.githubusercontent.com/22857964/180199206-b8e0a891-2f44-4fe8-b6f0-f05d7cc94ae7.png">

这是传值file的地方
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/22857964/180199459-378bbf69-552b-47c1-a76e-527220994e43.png">

**Comment by hfh1999** [comment]
你好，有空的时候我会再帮你看一下

**Comment by xiaokyo** [comment]
> 你好，有空的时候我会再帮你看一下

好的, 麻烦了

**Comment by xiaokyo** [comment]
终于成功了

**Comment by xiaokyo** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/22857964/181494939-9a52568b-d816-446e-bb8e-c09de03a0990.png">

**Comment by xiaokyo** [comment]
现在感觉加个线程或者异步来批量分片好像就可以优化上传速度

**Comment by hfh1999** [comment]
你好请问你后来是如何解决的呢？是哪里出了问题。

**Comment by xiaokyo** [comment]
就是chunk的写法找到了
<img width="743" alt="image" src="https://user-images.githubusercontent.com/22857964/183253946-c56f94df-c464-4c88-932f-fba469dfd011.png">

**Comment by xiaokyo** [comment]
https://github.com/xiaokyo/rs-baidu-sdk/blob/fe4390264aade0ef03a6f68446ab7370da7cd6a8/src/lib/pan.rs#L415
